### PR TITLE
#53 fix for filter, post and update

### LINKED ISSUE #53: [BUGFIX] Issue on create, get list and update video
## Issues
- Filter are `kabkota_id`, `title`, and `category_id`
- Error when post video
- Update video can be just one field

## Tasks
- [x] add filter `kabkota_id`, `title` and `category_id`
- [x] add checker when post video for status
- [x] update request body for update

### PR DESCRIPTION
**Pull request by setiadijoe**
close #53 
- fix filter `kabkota_id`
- add filter `title` and `category_id`
- adjust for user can update just one field
- adjust for checker of status that get from client

### CODE REVIEW

File: repository/mysql/helper_query.go [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+func updateQuery(ctx context.Context, fields ...string) string {
+	var query bytes.Buffer
+	query.WriteString(fmt.Sprintf(" %s = :%s ", fields[0], fields[0]))
+	if len(fields) > 1 {
+		for i := 1; i < len(fields); i++ {
+			query.WriteString(fmt.Sprintf(" , %s = :%s ", fields[i], fields[i]))
+		}
+	}
+	return query.String()
+}
```
Comment (aldidoanta) [inline repository/mysql/helper_query.go:48]: @setiadijoe since we are moving `updateQuery()` from `mysql.go` to `helper_query.go`, do we need adjustments to existing codebase? Like, changing import namespaces or something.

**Review by firmanJS — APPROVED** [review]

File: repository/mysql/helper_query.go (hunk 1 above)
Comment (setiadijoe) [reply repository/mysql/helper_query.go:48]: nope, because it is still in one package not different package. In golang you can create several files in one package or folder

File: repository/mysql/helper_query.go [hunk 2]
```diff
@@ -0,0 +1,48 @@
+package mysql
```
Comment (setiadijoe) [inline repository/mysql/helper_query.go:1]: you can see here @aldidoanta , it is still same package

**Review by aldidoanta — APPROVED** [review]
